name: binary-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-binary:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: build binary and publish GitHub release
    steps:
      - name: declare some variables
        id: vars
        run: |
          echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: |
          go mod download
      - name: Build
        run: |
          CGO_ENABLED=0 go build -v -o rotating-rsync-backup-linux-amd64 .
          ls -alh
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "rotating-rsync-backup-linux-amd64"
          artifactErrorsFailBuild: true
          # tag: "${{ steps.vars.outputs.SHA_SHORT }}"
